export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const SET_CART_ITEMS_FROM_LOCAL = "SET_CART_ITEMS_FROM_LOCAL";
export const UPDATE_CART_ITEMS_ON_LOAD = "UPDATE_CART_ITEMS_ON_LOAD";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const UPDATE_ITEM_QUANTITY = "UPDATE_ITEM_QUANTITY";
export const EMPTY_CART = "EMPTY_CART";
export const SET_GUEST_DELIVERY_ADDRESS = "SET_GUEST_DELIVERY_ADDRESS";
