export const SET_WISHLIST_ITEMS = "SET_WISHLIST_ITEMS";
export const ADD_ITEM_TO_WISHLIST = "ADD_ITEM_TO_WISHLIST";
export const REMOVE_ITEM_FROM_WISHLIST = "REMOVE_ITEM_FROM_WISHLIST";
export const UPDATE_WISHLIST_ITEMS_AVAILABILITY =
  "UPDATE_WISHLIST_ITEMS_AVAILABILITY";
