export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const RESET_SEARCH_TERM = "RESET_SEARCH_TERM";
export const ERROR_FETCH_CATEGORIES = "ERROR_FETCH_CATEGORIES";
