export const SET_PRODUCTS = "SET_PRODUCTS";
export const FILTER_PRODUCTS_BY_KEYWORD = "FILTER_PRODUCTS_BY_KEYWORD";
export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
export const RESET_FILTERED_PRODUCTS = "RESET_FILTERED_PRODUCTS";
